---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: naincykumari123/capstone:1.01
        imagePullPolicy: IfNotPresent
        name: myweb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  ports:
    port: 80
    protocol: TCP
  selector:
    app: myweb
